### ISSUE TITLE
Setting log_handler to = None doesn't seem to be working

### ISSUE THREAD

**Issue by ComatoseHub** [cloudwithax/pomice#40]
I have dictconfig setup for my logging so I can have multiple handlers and pull discord logs and bot logs separately. I setup a section for pomice and set the handler to none and it still seems to use the default handler.

**Comment by cloudwithax** [comment]
Pomice logs by default, this is the intended behavior. It is advised that if you want to use a custom handler that you set it in the `log_handler` parameter when you create the node.

**Comment by ComatoseHub** [comment]
Gotcha so there is no way to get the logging to console and a file?

**Comment by cloudwithax** [comment]
You can output to console and a file by adding a custom logging handler that has a stream handler that prints to stdout and that also has a file handler to also output all logs to a file of your choice.
https://stackoverflow.com/questions/13733552/logger-configuration-to-log-to-file-and-print-to-stdout

**Comment by ComatoseHub** [comment]
Got it I will see what I can figure out I don't want to have to reconfigure my whole logging setup thanks for the quick response and info though.
