### ISSUE TITLE
Node Connection Error unhandled

### ISSUE THREAD

**Issue by DTheIcyDragon** [cloudwithax/pomice#53]
```
Task exception was never retrieved
future: <Task finished name='Task-1845' coro=<Node.connect() done, defined at /usr/local/lib/python3.11/site-packages/pomice/pool.py:450> exception=NodeConnectionFailure("The connection to node 'FREE94' failed.")>
Traceback (most recent call last
  File "/usr/local/lib/python3.11/site-packages/pomice/pool.py", line 502, in connect
    raise NodeConnectionFailure(
pomice.exceptions.NodeConnectionFailure: The connection to node 'FREE94' failed.
```
This error occured multiple hundred times in my log today, I don't know what happens there but I don't get it fixed.
[log.txt](https://github.com/cloudwithax/pomice/files/11898941/log.txt)
Maybe you know what happend there and can fix it, the error pointed (as far as I saw) not into my code only into asyncio and pomice packages

best regards DTheIcyDragon

**Comment by cloudwithax** [comment]
a GAI error usually isnt the clients fault and is a result either from your servers ISP or whatever lavalink servers you're connecting to. I would suggest contacting them and making sure theres no issues on their end.
