### ISSUE TITLE
Soundcloud Support

### ISSUE THREAD

**Issue by alluding** [cloudwithax/pomice#61]
Does this have any SoundCloud support? I'm making a Discord bot, and currently, it only supports Apple Music, YouTube, and Spotify that I know of. Is there any SoundCloud functionality?

**Comment by cloudwithax** [comment]
yes, pomice supports soundcloud since its default with lavalink. this also goes for any other supported source by lavalink as well.

**Comment by alluding** [comment]
> yes, pomice supports soundcloud since its default with lavalink. this also goes for any other supported source by lavalink as well.

Can you give examples? I tried feeding my bot SoundCloud links, and for some odd reason, no results were returned.

**Comment by cloudwithax** [comment]
what version lavalink are you using? is soundcloud sources blocked?

**Comment by alluding** [comment]
> what version lavalink are you using? is soundcloud sources blocked?

I'm using the latest version, do you have a Discord or email I can contact you by? I can share my code.

**Comment by alluding** [comment]
Hey, I figured it out. I had to manually feed the search type and add a check for Soundcloud URLs.

**Comment by alluding** [comment]
Actually, I'm stuck again. When it comes to adding filter-based commands, it says that `tag` is required. I looked through the docs, and it doesn't seem to explain what `tag` is. Could you please explain?

**Comment by cloudwithax** [comment]
closing this issue, address all further issues in our discord https://discord.gg/r64qjTSHG8
